### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kitzler-walli** [rothren/XplotterTools#1]
When I try to generate the gcode for my own 24bit Bitmap I receive a "segmentation fault" error.
I used Ubuntu to compile the file with 
`gcc main.c -o test -lm -std=gnu99`

Can you tell me whats wrong here?

**Comment by rothren** [comment]
Well, a segmentation fault is a really vague error, but I would guess that either your bmp format differs from mine or you try to do it with a big picture... I added a default image (that works by me) on the project, could you try with my bmp?

**Comment by kitzler-walli** [comment]
I'm currently trying - the program still works on your panda file - the g-file is currently 1.77 GB large.
Which is the correct size for the gfile of the panda image?

I stopped the program now - the g-file is about 28GB - I'm still using the panda image.
On which platform are you programming this? I tried with Ubuntu and MacOS - I'll try windows next.

**Comment by rothren** [comment]
Strange... mine is 30Mo big!
I do everything on Windows.

**Comment by kitzler-walli** [comment]
Which IDE are you using? I just tried with VS2017 - now there seems some dependency missing. It cannot locate stdio.h
Maybe you could post the exe file somewhere?

**Comment by rothren** [comment]
Codeblocks with mingw

**Comment by rothren** [comment]
[LaserTools.zip](https://github.com/rothren/XplotterTools/files/1791301/LaserTools.zip)

**Comment by kitzler-walli** [comment]
I just installed MiniGW and it works now - what an odyssey - took me 4 hours to get this to run. Thx for your support.

**Comment by rothren** [comment]
No Problem, I'm glad my little project is used :)
